package com.c6823821.videolinktool

import android.content.Context
import java.io.File

object CookieStore {
    private const val FILE_NAME = "douyin.cookies.txt"

    fun file(context: Context): File = File(context.filesDir, FILE_NAME)

    fun hasDouyinCookies(context: Context? = null): Boolean {
        if (context == null) return false
        val value = file(context)
        return value.exists() && value.length() > 80
    }

    fun saveFromHeader(context: Context, cookieHeader: String) {
        val entries = cookieHeader.split(';').mapNotNull { part ->
            val item = part.trim()
            val index = item.indexOf('=')
            if (index <= 0) null else item.substring(0, index).trim() to item.substring(index + 1).trim()
        }.filter { it.first.isNotBlank() && it.second.isNotBlank() }
        if (entries.isEmpty()) throw IllegalStateException("没有拿到抖音 Cookie，请先完成页面验证")

        val lines = mutableListOf("# Netscape HTTP Cookie File", "# Generated by VideoLinkTool")
        val domains = listOf("www.douyin.com", ".douyin.com", "www.iesdouyin.com", ".iesdouyin.com")
        domains.forEach { domain ->
            entries.forEach { (name, value) ->
                if ('\t' in name || '\n' in name || '\t' in value || '\n' in value) return@forEach
                lines += listOf(domain, "TRUE", "/", "FALSE", "1893456000", name, value).joinToString("\t")
            }
        }
        file(context).writeText(lines.joinToString("\n") + "\n", Charsets.UTF_8)
    }
}
